name:                pg-analyze
version:             0.1.0.0
github:              "githubuser/pg-analyze"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pg-analyze#readme>

dependencies:
- base >= 4.7 && < 5
- text >=1.2 && <1.3
- aeson >= 1.5.6.0
- directory >= 1.3 && < 1.4
- yaml >= 0.11.5
- HDBC >= 2.3 && < 2.5
- HDBC-postgresql >= 2.3 && < 2.5
- process >= 1.6.12.0
- vector >= 0.11 && < 0.13
- colonnade >= 1.1 && < 1.3
- transformers >= 0.5.6

library:
  source-dirs: src

executables:
  pg-analyze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pg-analyze

tests:
  pg-analyze-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pg-analyze
